### ISSUE TITLE
Docker compose up error

### ISSUE THREAD

**Issue by tamal-appsbee** [ever-co/ever-demand#1329]
Hi,

After cloning the project, If I use docker-compose up command. getting following error

![image](https://user-images.githubusercontent.com/8500385/99030349-c4b01f00-259a-11eb-9247-6779995be000.png)

**Comment by evereq** [comment]
@tamal-appsbee thank you for reporting! Think it's related to the recent update of `node:alpine` to Node 15 and for some reason that causes the issues you saw. E.g. https://stackoverflow.com/questions/64543012/exdev-cross-device-link-not-permitted-rename-usr-local-lib-node-modules-npm. So the temporary workaround could be to change `FROM node:alpine` to `FROM node:14.15.0-alpine` in all Dockerfiles (in .deploy folder). 

We are looking into other possible fixes and will revert back here.

**Comment by tamal-appsbee** [comment]
@evereq Thanks

**Comment by evereq** [comment]
We are working on optimizing/fixing docker in https://github.com/ever-co/ever-demand/issues/1195, so closing this ticket in favor of that ticket.
